version: "2"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: db
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8

volumes:
  mysql-data:
